import { SlidersHorizontal, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import type { ListingFilters, ListingFilterUpdate } from "@/types/property";
const localities=["Adyar","Anna Nagar","Guindy","OMR","Perungudi","Porur","T Nagar","Tambaram","Thoraipakkam","Velachery"];
const selectValue=(value:string)=>value==="all"?undefined:value;
function Controls({filters,onChange}:{filters:ListingFilters;onChange:(next:ListingFilterUpdate)=>void}){return <div className="grid gap-4 lg:grid-cols-5"><Select value={filters.locality??"all"} onValueChange={(v)=>onChange({locality:selectValue(v)})}><SelectTrigger aria-label="Locality"><SelectValue placeholder="Locality"/></SelectTrigger><SelectContent><SelectItem value="all">All localities</SelectItem>{localities.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={filters.bedroom?.toString()??"all"} onValueChange={(v)=>onChange({bedroom:v==="all"?undefined:Number(v)})}><SelectTrigger aria-label="Bedrooms"><SelectValue placeholder="BHK"/></SelectTrigger><SelectContent><SelectItem value="all">Any BHK</SelectItem>{[1,2,3,4].map(x=><SelectItem key={x} value={String(x)}>{x===4?"4+":x} BHK</SelectItem>)}</SelectContent></Select><Select value={filters.property_type??"all"} onValueChange={(v)=>onChange({property_type:selectValue(v)})}><SelectTrigger aria-label="Property type"><SelectValue placeholder="Property type"/></SelectTrigger><SelectContent><SelectItem value="all">All types</SelectItem>{["Apartment","Villa","Penthouse","Independent House"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={filters.max_price?.toString()??"all"} onValueChange={(v)=>onChange({max_price:v==="all"?undefined:Number(v)})}><SelectTrigger aria-label="Price range"><SelectValue placeholder="Price range"/></SelectTrigger><SelectContent><SelectItem value="all">Any price</SelectItem><SelectItem value="7500000">Under ₹75L</SelectItem><SelectItem value="15000000">Under ₹1.5Cr</SelectItem><SelectItem value="25000000">Under ₹2.5Cr</SelectItem></SelectContent></Select><Select value={filters.furnishing??"all"} onValueChange={(v)=>onChange({furnishing:selectValue(v)})}><SelectTrigger aria-label="Furnishing"><SelectValue placeholder="Furnishing"/></SelectTrigger><SelectContent><SelectItem value="all">Any furnishing</SelectItem>{["Furnished","Semi-furnished","Unfurnished"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><label className="flex items-center justify-between gap-3 text-sm lg:col-span-1"><span>Verified only</span><Switch checked={!!filters.is_verified} onCheckedChange={(v)=>onChange({is_verified:v||undefined})}/></label><label className="flex items-center justify-between gap-3 text-sm lg:col-span-1"><span>Live listings only</span><Switch checked={!!filters.is_live} onCheckedChange={(v)=>onChange({is_live:v||undefined})}/></label></div>}
export function FilterBar({filters,onChange,onClear}:{filters:ListingFilters;onChange:(next:ListingFilterUpdate)=>void;onClear:()=>void}){return <div className="border-b border-border bg-card"><div className="mx-auto max-w-[1440px] px-4 py-4 sm:px-6 lg:px-10"><div className="hidden items-center gap-5 lg:grid lg:grid-cols-[minmax(0,1fr)_auto]"><Controls filters={filters} onChange={onChange}/><Button variant="ghost" onClick={onClear}><X/>Clear filters</Button></div><div className="flex items-center justify-between lg:hidden"><p className="text-sm font-medium">Refine your search</p><Sheet><SheetTrigger asChild><Button variant="outline"><SlidersHorizontal/>Filters</Button></SheetTrigger><SheetContent side="bottom" className="max-h-[90vh] overflow-y-auto rounded-t-xl"><SheetHeader className="text-left"><SheetTitle>Filters</SheetTitle><SheetDescription>Refine properties across Chennai.</SheetDescription></SheetHeader><div className="mt-6"><Controls filters={filters} onChange={onChange}/><Button variant="outline" className="mt-6 w-full" onClick={onClear}><X/>Clear filters</Button></div></SheetContent></Sheet></div></div></div>}
