import { useCallback, useState } from "react";
import { Header } from "./Header";
import { SearchHero } from "./SearchHero";
import { FilterBar } from "./FilterBar";
import { PropertyCard } from "./PropertyCard";
import { PropertyDetail } from "./PropertyDetail";
import { OffsetPagination } from "./Pagination";
import { EmptyState, ErrorState, SkeletonGrid } from "./States";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useListings } from "@/hooks/useListings";
import type { AuthSession } from "@/services/auth";
import type { Listing, ListingSort } from "@/types/property";

export function PropertiesPage({session,onLogout}:{session:AuthSession;onLogout:()=>void}){const listings=useListings(9);const [selected,setSelected]=useState<Listing|null>(null);const [favorites,setFavorites]=useState<Set<string>>(new Set());const toggleFavorite=useCallback((id:string)=>setFavorites((current)=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next}),[]);return <div className="min-h-screen bg-background"><Header name={session.displayName} onLogout={onLogout}/><SearchHero filters={listings.filters} onChange={listings.updateFilters}/><FilterBar filters={listings.filters} onChange={listings.updateFilters} onClear={listings.clearFilters}/><main className="mx-auto max-w-[1440px] px-4 py-8 sm:px-6 lg:px-10 lg:py-10"><div className="mb-7 grid grid-cols-[minmax(0,1fr)_auto] items-end gap-4"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-[.14em] text-primary">Curated for you</p><h2 className="mt-2 font-display text-lg font-semibold sm:text-3xl">Properties in Chennai</h2>{listings.data&&<p className="mt-1 text-sm text-muted-foreground">{listings.data.total} homes match your search</p>}</div><Select value={listings.sort} onValueChange={(v)=>{listings.setSort(v as ListingSort);listings.setOffset(0)}}><SelectTrigger className="w-[140px] bg-card sm:w-[190px]" aria-label="Sort properties"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="relevance">Relevance</SelectItem><SelectItem value="price_asc">Price: Low to High</SelectItem><SelectItem value="price_desc">Price: High to Low</SelectItem><SelectItem value="newest">Newest</SelectItem></SelectContent></Select></div>{listings.isLoading?<SkeletonGrid/>:listings.error?<ErrorState onRetry={listings.retry}/>:!listings.data?.results.length?<EmptyState onClear={listings.clearFilters}/>:<><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{listings.data.results.map((item)=><PropertyCard key={item.listing_id} listing={item} favorite={favorites.has(item.listing_id)} onFavorite={()=>toggleFavorite(item.listing_id)} onOpen={()=>setSelected(item)}/>)}</div><OffsetPagination offset={listings.offset} limit={listings.limit} total={listings.data.total} hasMore={listings.data.has_more} loading={listings.isLoading} onOffsetChange={listings.setOffset}/></>}<PropertyDetail listing={selected} onClose={()=>setSelected(null)}/></main></div>}
