/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RentalsRouteImport } from './routes/rentals'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ListingsListingIdRouteImport } from './routes/listings/$listingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRoute = RentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsListingIdRoute = ListingsListingIdRouteImport.update({
  id: '/listings/$listingId',
  path: '/listings/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/projects': typeof ProjectsRoute
  '/rentals': typeof RentalsRoute
  '/saved': typeof SavedRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/projects': typeof ProjectsRoute
  '/rentals': typeof RentalsRoute
  '/saved': typeof SavedRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/projects': typeof ProjectsRoute
  '/rentals': typeof RentalsRoute
  '/saved': typeof SavedRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/insights'
    | '/projects'
    | '/rentals'
    | '/saved'
    | '/listings/$listingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/insights'
    | '/projects'
    | '/rentals'
    | '/saved'
    | '/listings/$listingId'
  id:
    | '__root__'
    | '/'
    | '/insights'
    | '/projects'
    | '/rentals'
    | '/saved'
    | '/listings/$listingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InsightsRoute: typeof InsightsRoute
  ProjectsRoute: typeof ProjectsRoute
  RentalsRoute: typeof RentalsRoute
  SavedRoute: typeof SavedRoute
  ListingsListingIdRoute: typeof ListingsListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals': {
      id: '/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof RentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$listingId': {
      id: '/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/listings/$listingId'
      preLoaderRoute: typeof ListingsListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InsightsRoute: InsightsRoute,
  ProjectsRoute: ProjectsRoute,
  RentalsRoute: RentalsRoute,
  SavedRoute: SavedRoute,
  ListingsListingIdRoute: ListingsListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
